### ISSUE TITLE
Make website auto update if changes in mobirise are made.

### ISSUE THREAD

**Issue by VonSub** [BetterToken/www_bettertoken.com#3]
Latest pushed changes not showing on staging, make this automatically update.

**Comment by PeterNashaat** [comment]
- Webhook fixed and now working in staging and production websites

**Comment by VonSub** [comment]
> * Webhook fixed and now working in staging and production websites

Nice!

**Comment by VonSub** [comment]
@PeterNashaat made changes in staging code, they are not showing up on the www2.

**Comment by VonSub** [comment]
confirmed now
