### ISSUE TITLE
Setup Wiki

### ISSUE THREAD

**Issue by VonSub** [BetterToken/www_bettertoken.com#6]
Setup BetterToken Wiki
- [x]  Hosted on OVH node 
- [x]  Auto updating
- [x]  Point wiki.bettertoken.com here

**Comment by PeterNashaat** [comment]
wiki is deployed ,auto deployment enabled and hosted in ovh 
url : https://info.bettertoken.com/#/
development url : https://www2.info.bettertoken.com/#/

**Comment by VonSub** [comment]
url should be: wiki.bettertoken.com
staging: wiki2.bettertoken.com 

for all wikis we us this naming convention

**Comment by VonSub** [comment]
wiki is there, naming convention will be changed soon.

https://github.com/threefoldtech/OpenPublish/issues/10
